# Backend nixpacks configuration for Coolify
[phases.setup]
nixPkgs = ["nodejs_24", "npm-10_x"]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = []

[start]
cmd = "npm run prod"

[variables]
NODE_ENV = "production"
