name: "Welcome New Contributors"

on:
    issues:
        types: [opened]
    pull_request_target:
        types: [opened]

jobs:
    welcome-new-contributor:
        runs-on: ubuntu-latest
        steps:
            - name: "Greet the contributor"
              uses: garg3133/welcome-new-contributors@v1.2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  issue-message: "🎉 Welcome to ZettaNote, @contributor_name! Thank you for opening your first issue. We're excited to have you here! 🚀\n\nOur team will review your issue soon. In the meantime, feel free to explore our [Contributing Guidelines](../CONTRIBUTING.md) and join the conversation. We appreciate your contribution to making ZettaNote better! 💡"
                  pr-message: "🎊 Awesome work, @contributor_name! Thank you for opening your first Pull Request to ZettaNote! 🌟\n\nWe're thrilled to have you contribute to our project. A maintainer will review your PR soon. While you wait, make sure your changes follow our [Code of Conduct](../CODE_OF_CONDUCT.md) and [Contributing Guidelines](../CONTRIBUTING.md).\n\nThank you for being part of our community! 🙌"
